import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  BarChart4,
  BookOpen,
  Box,
  Building2,
  Calendar,
  Check,
  CheckCircle,
  ChevronsUpDown,
  Clock,
  CreditCard,
  House,
  Laptop,
  Layers,
  LayoutDashboard,
  Loader,
  Menu,
  Moon,
  Plus,
  Settings,
  Shield,
  Sun,
  Trash,
  Users,
  Wallet,
  X,
} from "lucide-react";

export const Icons = {
  alert: AlertCircle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  barChart: BarChart4,
  building: Building2,
  calendar: Calendar,
  check: Check,
  checkCircle: CheckCircle,
  chevronsUpDown: ChevronsUpDown,
  clock: Clock,
  close: X,
  creditCard: CreditCard,
  dashboard: LayoutDashboard,
  home: BookOpen,
  house: House,
  laptop: Laptop,
  loader: Loader,
  logo: Layers,
  menu: Menu,
  moon: Moon,
  payments: Wallet,
  plus: Plus,
  settings: Settings,
  shield: Shield,
  sun: Sun,
  trash: Trash,
  unit: Box,
  users: Users,
};
